# Generated by Django 5.2.9 on 2025-12-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('normal_price', models.FloatField(default=0)),
                ('dukkan', models.FloatField(default=0)),
                ('kian', models.FloatField(default=0)),
                ('competitor', models.FloatField(default=0)),
                ('othaim', models.FloatField(default=0)),
                ('amazon', models.FloatField(default=0)),
            ],
        ),
    ]
