# Generated by Django 5.2.9 on 2025-12-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='normal_price',
        ),
        migrations.AddField(
            model_name='product',
            name='regular_price',
            field=models.FloatField(blank=True, null=True, verbose_name='السعر العادي'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amazon',
            field=models.FloatField(blank=True, null=True, verbose_name='امازون'),
        ),
        migrations.AlterField(
            model_name='product',
            name='competitor',
            field=models.FloatField(blank=True, null=True, verbose_name='المنافس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dukkan',
            field=models.FloatField(blank=True, null=True, verbose_name='الدكان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kian',
            field=models.FloatField(blank=True, null=True, verbose_name='كيان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='othaim',
            field=models.FloatField(blank=True, null=True, verbose_name='العثيم'),
        ),
    ]
