# Generated by Django 5.2.9 on 2025-12-14 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_product_updated_at_alter_product_amazon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amazon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='أمازون'),
        ),
        migrations.AlterField(
            model_name='product',
            name='competitor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='المنافس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dukkan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='الدكان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kian',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='كيان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='othaim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='العثيم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='السعر العادي'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخر تحديث'),
        ),
    ]
